name: CI Android

on:
  push:
    branches: [main]
    paths:
      - 'android/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.3
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.3
      - name: Install base modules
        run: yarn; yarn build
      - name: Kotlin Linter
        uses: vroy/gha-kotlin-linter@v4
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
      - name: Build with Library with Gradle and check lints
        run: cd android;./gradlew build test
      - name: Unit tests results
        uses: actions/upload-artifact@v2
        with:
          name: play-unit-tests-results
          path: android/build/reports/tests/testPlayDebugUnitTest/index.html
