name: CI

on:
  push:
    branches: [main, next]
    paths:
      - 'src/**'
      - '*.json'
      - '*.js'
      - '*.lock'
      - 'IapExample/src/**'
      - 'IapExample/*.json'
      - 'IapExample/*.js'
      - 'IapExample/*.lock'
      - 'IapExample/*.tsx'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Build typescript & flow
        run: yarn build

      - name: Run Validation steps including Linting and Unit Tests
        run: yarn validate --no-verify
